#!/bin/bash
# Generates a linker version script that marks every cu*/nvml* wrapper
# function defined inside SoftMig as globally visible (default visibility)
# while everything else stays hidden. This is what makes LD_PRELOAD
# interposition work for applications that statically link -lcuda/-lnvidia-ml
# (e.g. gpu-burn, cuda-samples) instead of resolving symbols through the
# CUDA runtime's dlsym() path.
#
# Usage: gen_version_script.sh <src_dir> <output_file>
set -eu

SRC_DIR="${1:-.}"
OUT="${2:-/dev/stdout}"

# Collect every "CUresult cuFoo(...)" or "nvmlReturn_t nvmlBar(...)" top-level
# definition in our own source tree. We also explicitly whitelist dlsym and a
# couple of bootstrap symbols.
SYMS=$(
  {
    grep -hE '^(CUresult|nvmlReturn_t|void|int)[[:space:]]+(cu|nvml)[A-Za-z0-9_]+[[:space:]]*\(' \
      "$SRC_DIR"/cuda/*.c "$SRC_DIR"/nvml/*.c "$SRC_DIR"/utils.c "$SRC_DIR"/libsoftmig.c \
      "$SRC_DIR"/multiprocess/*.c 2>/dev/null | \
      sed -E 's/^(CUresult|nvmlReturn_t|void|int)[[:space:]]+([A-Za-z0-9_]+).*/\2/' ;
    # Always-exported bootstrap symbols:
    echo dlsym
    echo cuMemGetInfo
    echo cuMemGetInfo_v2
  } | sort -u
)

{
  echo "/* Auto-generated by gen_version_script.sh. Do not edit. */"
  # Unnamed (anonymous) version scope: exports the listed symbols WITHOUT
  # attaching a version suffix. That's crucial for LD_PRELOAD interposition:
  # apps (and libc) call symbols like dlsym, nvmlInit, etc. expecting the
  # unversioned or original-versioned entry. A named scope (e.g. SOFTMIG_1.0)
  # would tag our exports with @@SOFTMIG_1.0, preventing dlsym calls that
  # expect GLIBC_2.2.5 from resolving to our wrapper.
  echo "{"
  echo "  global:"
  while IFS= read -r s; do
    [ -n "$s" ] && echo "    $s;"
  done <<< "$SYMS"
  echo "  local:"
  echo "    *;"
  echo "};"
} > "$OUT"
